name: Deploy release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/shared-public-configs/.github/workflows/publish-public-npm-package.yml@master
    with:
      prepare-script: node prepare-release.mjs
